### ISSUE TITLE
Fabric 1.19.2 Crash

### ISSUE THREAD

**Issue by spunchbop121** [KrLite/Flash#1]
Crash after taking a screenshot in menu (mod menu modlist etc)
Ingame world screensots works properly.

Crash client: https://pastebin.com/7E47Vsxs

Logs: https://pastebin.com/1MDmE8kS

**Comment by KrLite** [comment]
Sorry for the late fix.
However, this bug is fixed in [`1.1.1`](https://modrinth.com/mod/flash/version/1.19-v1.1.1) with some other improvements and the support for `Minecraft 1.20~1.20.1`. Enjoy!
