### ISSUE TITLE
Add gif of screenshotting animation at Splash modrinth page.

### ISSUE THREAD

**Issue by andry4054** [KrLite/Flash#2]
Splash is real good tiny mod but needs a showcase of its work.  Sorry, didnt know where else to write or how to contact you.

**Comment by andry4054** [comment]
*Flash. Not splash. Flash

**Comment by KrLite** [comment]
Good idea! I'll take it pretty.

**Comment by KrLite** [comment]
Done!
I actually prepared 4 different gifs, but https://ezgif.com is not responding at all after the first conversion, so only 1 gif now :(

**Comment by KrLite** [comment]
I've got all the gifs!

**Comment by andry4054** [comment]
perfecto!
